services:

  mariadb:
    container_name: mariadb
    image: fgabler/mariadb:latest
    build:
      context: ./requirements/mariadb/
      dockerfile: mariadb.Dockerfile
    env_file: ".env"
    networks:
      - inception_net
    volumes:
      - mariadb-vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    image: fgabler/wordpress:latest
    env_file: ".env"
    build: 
      context: ./requirements/wordpress
      dockerfile: wordpress.Dockerfile
    networks:
      - inception_net
    volumes:
      - wp-and-ngix-vol:/var/www/html/mysite
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: fgabler/nginx:latest
    env_file: ".env"
    build:
      context: ./requirements/nginx/
      dockerfile: nginx.Dockerfile
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - wp-and-ngix-vol:/var/www/html/mysite
    depends_on:
      - wordpress




networks:
  inception_net:
    name: 'inception_net'
    driver: bridge

volumes:
  wp-and-ngix-vol:
    name: 'wp-and-nginx-dir'
    driver: local
    driver_opts:
      device: "wp_and_nginx_dir"
      o: bind
      type: none
  mariadb-vol:
    name: 'mariadb-vol'
    driver: local
    driver_opts:
      device: "mariadb-dir"
      o: bind
      type: none

