services:

  mariadb:
    container_name: mariadb
    image: fgabler/mariadb:latest
    build:
      context: ./requirements/mariadb/
      dockerfile: mariadb.Dockerfile
    env_file: ".env"
    networks:
      - inception_net
    volumes:
      - mariadb-vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always
    secrets:
      - maria-pass

  wordpress:
    container_name: wordpress
    image: fgabler/wordpress:latest
    env_file: ".env"
    build: 
      context: ./requirements/wordpress
      dockerfile: wordpress.Dockerfile
    networks:
      - inception_net
    volumes:
      - wp-and-ngix-vol:/var/www/html/mysite
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    secrets:
      - maria-pass
      - wp-db-user-pass
      - author_pass

  nginx:
    container_name: nginx
    image: fgabler/nginx:latest
    env_file: ".env"
    build:
      context: ./requirements/nginx/
      dockerfile: nginx.Dockerfile
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - wp-and-ngix-vol:/var/www/html/mysite
    depends_on:
      - wordpress
    restart: always




networks:
  inception_net:
    name: 'inception_net'
    driver: bridge

volumes:
  wp-and-ngix-vol:
    name: 'wp-and-nginx-dir'
    driver: local
    driver_opts:
      device: "/home/fgabler/data/wp_and_nginx_dir"
      o: bind
      type: none
  mariadb-vol:
    name: 'mariadb-vol'
    driver: local
    driver_opts:
      device: "/home/fgabler/data/mariadb-dir"
      o: bind
      type: none

secrets:
  maria-pass:
    file: ./../secrets/maria-pass.txt
  wp-db-user-pass:
    file: ./../secrets/wp-db-user-pass.txt
  author_pass:
    file: ./../secrets/author_pass.txt
  sql_root_pass:
    file: ./../secrets/sql_root_pass.txt
